<?php

/**
 * BaseOnlineUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property Profile $Profile
 * 
 * @method integer    getUserId()  Returns the current record's "user_id" value
 * @method Profile    getProfile() Returns the current record's "Profile" value
 * @method OnlineUser setUserId()  Sets the current record's "user_id" value
 * @method OnlineUser setProfile() Sets the current record's "Profile" value
 * 
 * @package    capsoff.net
 * @subpackage model
 * @author     Моисеев Данил
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOnlineUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('online_user');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'user_id',
             'foreign' => 'user_id',
             'onDelete' => 'CASCADE'));
    }
}