<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Answer extends BaseAnswer
{
	public function updateLuceneIndex()
	{
		$index = AnswerTable::getLuceneIndex();

		// удалить существующие записи
		foreach ($index->find('pk:'.$this->getId()) as $hit)
			{
				$index->delete($hit->id);
			}

		$doc = new Zend_Search_Lucene_Document();

		// сохраняем первичный ключ для идентификации ее в результатах поиска
		$doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));

		// индексируем поля
		$doc->addField(Zend_Search_Lucene_Field::UnStored('text', $this->getText(), 'utf-8'));

		// добавляем работу в индекс
		$index->addDocument($doc);
		$index->commit();
	}

	public function save(Doctrine_Connection $conn = null)
		{
			if ($this->isNew())
				{
					$ret = parent::save($conn);

					$this->updateLuceneIndex();

					return $ret;
				}

			return parent::save($conn);
		}
}