<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Category extends BaseCategory
{
	public function __toString()
		{
			return $this->getName();
		}

	public function getCategoryPosts()
		{
			$q = PostTable::getFullPostQuery()
						->andWhere('p.category_id = ?',$this['id'])
						->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY);

			return $q;
		}
}