<?php

/**
 * Profile
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    forum
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Profile extends BaseProfile
{
	public function updateLuceneIndex()
	{
		$index = PostTable::getLuceneIndex();

		// удалить существующие записи
		foreach ($index->find('pk:'.$this->getId()) as $hit)
			{
				$index->delete($hit->id);
			}

		// не индексировать истекшие и не активированные вакансии
		if ($this->validate != null)
			{
				return;
			}

		$doc = new Zend_Search_Lucene_Document();

		// сохраняем первичный ключ вакансии для идентификации ее в результатах поиска
		$doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));

		// индексируем поля вакансии
		$doc->addField(Zend_Search_Lucene_Field::UnStored('fullname', $this->getFullname(), 'utf-8'));
		$doc->addField(Zend_Search_Lucene_Field::UnStored('know', $this->getKnow(), 'utf-8'));
		$doc->addField(Zend_Search_Lucene_Field::UnStored('want_know', $this->getWantKnow(), 'utf-8'));

		// добавляем работу в индекс
		$index->addDocument($doc);
		$index->commit();
	}


	public function getGroup()
		{
        	$q = Doctrine::getTable('sfGuardGroup')
        			->createQuery('g')
					->where('g.id IN (SELECT ug.group_id FROM sfGuardUserGroup ug WHERE ug.user_id = ?)',$this->getUserId());

        	return $q->fetchOne();
		}

	public function save(Doctrine_Connection $conn = null)
		{
			if ($this->isNew())
				{
					if ($this->fullname == '') { $this->setFullname($this->email); }
                }

			$ret = parent::save($conn);

			$this->updateLuceneIndex();

			return $ret;
		}

	public function delete(Doctrine_Connection $conn = null)
	{
		$index = ProfileTable::getLuceneIndex();

		foreach ($index->find('pk:'.$this->getId()) as $hit)
			{
				$index->delete($hit->id);
			}

		return parent::delete($conn);
	}
}
