<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends Doctrine_Table
{

	public function GetCloudTags()
		{

			$q = Doctrine_Query::create()
							->select('t.id, t.name, t.views')
							->from('Tag t')
							->orderBy('t.views')
							->setHydrationMode(Doctrine_CORE::HYDRATE_ARRAY);

			$tags = $q->execute();
			$q->free();

			return $tags;
		}

	public function getIndexTags()
		{
        	$q = Doctrine_Query::create()
							->select('t.id, t.name, t.views,
							          COUNT(DISTINCT p.id) AS posts')
							->from('Tag t, t.Posts p')
							->groupBy('t.id')
							->orderBy('t.name')
							->setHydrationMode(Doctrine_CORE::HYDRATE_ARRAY);

			$tags = $q->execute();
			$q->free();

			return $tags;
		}
}