all:
  sfApplyPlugin:
    from:
      email: capsofff.net@yandex.ru
      fullname: capsoff.net Administrator

  sf_captchagd:
          image_width:                180 # image width in pixels
          image_height:               60 # image height in pixels
          chars:                      "023456789" # possible chars in captcha
          length:                     5 # length of captcha
          font_size:                  25 # font size
          force_new_captcha:          true # if true - captcha regenerated EVERY request, even if user input true value before

          # possible chars colors
          font_color:                 ["252525", "8b8787", "550707", "3526E6", "88531E"]

          # chars fonts
          fonts:                      [ "molten/molten.ttf", "planet_benson/Planetbe.ttf"]
          background_color:           DDDDDD # image background color
          border_color:               000000 # image border color